
ALTER TABLE public.campaigns
  ADD COLUMN IF NOT EXISTS meta_impressions INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS meta_clicks INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS meta_reach INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS meta_last_synced_at TIMESTAMPTZ;

ALTER TABLE public.ad_spend
  ADD COLUMN IF NOT EXISTS source TEXT NOT NULL DEFAULT 'manual';
